# Frontend chat widget service
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
      - NEXT_PUBLIC_API_URL_EXTERNAL=http://127.0.0.1:8000

    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
    restart: always




networks:
  app-network:
    driver: bridge
